/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2019-Present Datadog, Inc.
 */

import Foundation

/// Per-tracer client-side stats payload.
///
/// See https://github.com/DataDog/datadog-agent/blob/main/pkg/proto/datadog/trace/stats.proto
///
/// Field names and order match the mobile-relevant subset of `ClientStatsPayload.EncodeMsg`
/// in `stats_gen.go`. Agent-side fields (`AgentAggregation`, `ContainerID`, `GitCommitSha`,
/// `ImageTag`, `ProcessTagsHash`, `ProcessTags`) are intentionally omitted because the mobile
/// SDK uploads to intake directly without a Datadog Agent. The encoded payload is
/// byte-for-byte aligned with the Android implementation to keep cross-platform parity.
///
/// Wire-format encoding is generated by Swift's synthesized `Encodable` conformance:
/// `CodingKeys` declaration order drives the field order on the wire.
internal struct ClientStatsPayload: Encodable {
    let hostname: String
    let env: String
    let version: String
    let stats: [ClientStatsBucket]
    let tracerVersion: String
    let runtimeID: String
    let sequenceNumber: UInt64
    let service: String

    /// Platform identifier on the wire, matching Android's `"android"`. Distinct from the
    /// spans `lang` tag (`"swift"`); the stats intake keys off platform.
    private let lang = "ios"

    private enum CodingKeys: String, CodingKey {
        case hostname = "Hostname"
        case env = "Env"
        case version = "Version"
        case stats = "Stats"
        case lang = "Lang"
        case tracerVersion = "TracerVersion"
        case runtimeID = "RuntimeID"
        case sequenceNumber = "Sequence"
        case service = "Service"
    }

    init(
        hostname: String,
        env: String,
        version: String,
        service: String,
        tracerVersion: String,
        runtimeID: String,
        sequenceNumber: UInt64,
        stats: [ClientStatsBucket]
    ) {
        self.hostname = hostname
        self.env = env
        self.version = version
        self.service = service
        self.tracerVersion = tracerVersion
        self.runtimeID = runtimeID
        self.sequenceNumber = sequenceNumber
        self.stats = stats
    }
}

/// A time-bucketed group of `ClientGroupedStats` for a fixed `[start, start + duration[` window.
/// (Half-open at the right: a span ending exactly at `start + duration` belongs to the next bucket.)
///
/// Field names and order match the mobile-relevant subset of `ClientStatsBucket.EncodeMsg`
/// in `stats_gen.go`. `AgentTimeShift` is intentionally omitted because the mobile SDK is
/// agent-less. Wire-format encoding is generated by Swift's synthesized `Encodable` conformance.
internal struct ClientStatsBucket: Encodable {
    let start: UInt64
    let duration: UInt64
    let stats: [ClientGroupedStats]

    private enum CodingKeys: String, CodingKey {
        case start = "Start"
        case duration = "Duration"
        case stats = "Stats"
    }
}

/// Per `(service, name, resource, ...)` aggregated stats within a single bucket.
///
/// Field names and order match the mobile-relevant subset of `ClientGroupedStats.EncodeMsg`
/// in `stats_gen.go`. Fields not yet in scope for the mobile v1 payload (`DBType`,
/// `HTTPMethod`, `HTTPEndpoint`, `SpanDerivedPrimaryTags`, `AdditionalMetricTags`) are
/// intentionally omitted; revisit when the v1.2.0 spec is updated for mobile.
/// `okSummary` and `errorSummary` carry the protobuf-encoded DDSketch summaries for the
/// OK and error latency distributions respectively. `Synthetics` is hardcoded `false`
/// (mobile SDK has no synthetic-test concept) and `GRPCStatusCode` is hardcoded `""`
/// (gRPC is not yet instrumented).
///
/// Wire-format encoding is generated by Swift's synthesized `Encodable` conformance:
/// `CodingKeys` declaration order drives the field order on the wire.
internal struct ClientGroupedStats: Encodable {
    let service: String
    let name: String
    let resource: String
    let httpStatusCode: UInt32
    let type: String
    let spanKind: String
    let isTraceRoot: Trilean
    let hits: UInt64
    let errors: UInt64
    let duration: UInt64
    let topLevelHits: UInt64
    let okSummary: Data
    let errorSummary: Data
    let peerTags: [String]
    let serviceSource: String

    private let synthetics = false
    private let grpcStatusCode = ""

    private enum CodingKeys: String, CodingKey {
        case service = "Service"
        case name = "Name"
        case resource = "Resource"
        case httpStatusCode = "HTTPStatusCode"
        case type = "Type"
        case hits = "Hits"
        case errors = "Errors"
        case duration = "Duration"
        case okSummary = "OkSummary"
        case errorSummary = "ErrorSummary"
        case synthetics = "Synthetics"
        case topLevelHits = "TopLevelHits"
        case spanKind = "SpanKind"
        case peerTags = "PeerTags"
        case isTraceRoot = "IsTraceRoot"
        case grpcStatusCode = "GRPCStatusCode"
        case serviceSource = "srv_src"
    }

    init(
        service: String,
        name: String,
        resource: String,
        httpStatusCode: UInt32,
        type: String,
        spanKind: String,
        isTraceRoot: Trilean,
        hits: UInt64,
        errors: UInt64,
        duration: UInt64,
        topLevelHits: UInt64,
        okSummary: Data,
        errorSummary: Data,
        peerTags: [String],
        serviceSource: String
    ) {
        self.service = service
        self.name = name
        self.resource = resource
        self.httpStatusCode = httpStatusCode
        self.type = type
        self.spanKind = spanKind
        self.isTraceRoot = isTraceRoot
        self.hits = hits
        self.errors = errors
        self.duration = duration
        self.topLevelHits = topLevelHits
        self.okSummary = okSummary
        self.errorSummary = errorSummary
        self.peerTags = peerTags
        self.serviceSource = serviceSource
    }
}
