# Dependabot configuration for GitHub Actions and Python dependencies
# This will automatically create PRs to update GitHub Actions and Python packages to their latest versions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gh-actions-packages:
        patterns:
          - "*"
  
  - package-ecosystem: "pip"
    directory: "/tools/issue_handler"
    schedule:
      interval: "monthly"
    groups:
      python-packages:
        patterns:
          - "*"
