platform :ios, '12.0'

target 'iOS-app-example-cocoapods' do
  use_frameworks!
  pod 'DatadogSDK', path: '../..'
  # Here we need to point to our fork as up-to-date `opentracing/opentracing-swift`'s podspec is not pushed to pod trunk
  pod 'OpenTracingSwift', :git => 'https://github.com/DataDog/opentracing-swift'
end
