version: 1
builder:
  configs:
    - platform: ios
      scheme: DatadogCore iOS
      documentation_targets: 
        - DatadogCore iOS
        - DatadogLogs iOS
        - DatadogTrace iOS
        - DatadogRUM iOS
        - DatadogSessionReplay iOS
        - DatadogCrashReporting iOS
        - DatadogWebViewTracking iOS
