load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("@rules_apple//apple:ios.bzl", "ios_unit_test")

swift_library(
    name = "DatadogTrace",
    srcs = glob(["Sources/**/*.swift"]),
    module_name = "DatadogTrace",
    copts = ["-enable-testing"],
    deps = [
        "//DatadogInternal",
        "@swiftpkg_opentelemetry_swift_core//:OpenTelemetryApi",
    ],
    visibility = ["//visibility:public"],
)

swift_library(
    name = "DatadogTraceTestsLib",
    srcs = glob(["Tests/**/*.swift"]),
    testonly = True,
    deps = [
        ":DatadogTrace",
        "//TestUtilities",
    ],
)

ios_unit_test(
    name = "DatadogTraceTests",
    bundle_id = "com.datadoghq.DatadogTraceTests",
    minimum_os_version = "12.0",
    deps = [":DatadogTraceTestsLib"],
)
