name: Run all-platform tests

on:
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  build:
    name: All-platform tests
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello
        run: echo 'Hello ${{ github.actor }} 👋.'
